//! Context Delivery — abstract transport for injecting context into agent sessions.
//!
//! Defines the `ContextDelivery` trait and `FileContextDelivery` implementation.
//! Future transports (ACPX, WebSocket) implement the same trait.

use std::io;
use std::path::{Path, PathBuf};

use async_trait::async_trait;

use super::memory::ColdMemoryRecord;

// ── ContextDelivery Trait ───────────────────────────────────────────

/// Abstract interface for delivering context to agent sessions.
///
/// Implementations handle the mechanics of reading progress data,
/// building context files, and injecting them into the session workspace.
#[async_trait]
pub trait ContextDelivery: Send + Sync {
    /// Inject context for a session into the project directory.
    ///
    /// Returns `Ok(true)` if context was written, `Ok(false)` if there was
    /// nothing to inject (e.g. no progress data yet).
    async fn inject_context(&self, session_key: &str, project_path: &Path) -> io::Result<bool>;

    /// Read raw progress data for a session.
    async fn read_progress(&self, session_key: &str) -> io::Result<String>;

    /// Read cold memory records from the persistent snapshot.
    async fn read_cold_memory(&self) -> io::Result<Vec<ColdMemoryRecord>>;

    /// Build the sidecar feedback hint string for a session.
    fn build_sidecar_hint(&self, session_key: &str) -> String;
}

// ── FileContextDelivery ─────────────────────────────────────────────

/// File-based context delivery — the default transport.
///
/// Reads progress from `{progress_dir}/{session_key}.md`,
/// reads cold memory from `{runtime_dir}/cold_memory_snapshot.json`,
/// and writes context to `{project_path}/.agent-hand-context.md`.
pub struct FileContextDelivery {
    pub progress_dir: PathBuf,
    pub runtime_dir: PathBuf,
}

impl FileContextDelivery {
    pub fn new(progress_dir: PathBuf, runtime_dir: PathBuf) -> Self {
        Self {
            progress_dir,
            runtime_dir,
        }
    }
}

#[async_trait]
impl ContextDelivery for FileContextDelivery {
    async fn inject_context(&self, session_key: &str, project_path: &Path) -> io::Result<bool> {
        let progress = match self.read_progress(session_key).await {
            Ok(content) => content,
            Err(_) => return Ok(false),
        };

        if progress.trim().is_empty() {
            return Ok(false);
        }

        // Take last 50 lines of progress
        let recent: String = progress
            .lines()
            .rev()
            .take(50)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect::<Vec<_>>()
            .join("\n");

        // Build cold memory read-back section
        let memory_section = self.build_memory_section().await;

        // Build sidecar hint section
        let sidecar_hint = self.build_sidecar_hint(session_key);

        let context = format!(
            "<!-- Auto-generated by agent-hand. Do not edit manually. -->\n\
             # Agent Progress: {}\n\n\
             ## Recent Activity\n\n\
             {}\n\
             {}{}\n",
            session_key, recent, memory_section, sidecar_hint
        );

        let context_path = project_path.join(".agent-hand-context.md");
        tokio::fs::write(&context_path, context).await?;
        Ok(true)
    }

    async fn read_progress(&self, session_key: &str) -> io::Result<String> {
        let progress_file = self.progress_dir.join(format!("{}.md", session_key));
        tokio::fs::read_to_string(&progress_file).await
    }

    async fn read_cold_memory(&self) -> io::Result<Vec<ColdMemoryRecord>> {
        let path = self.runtime_dir.join("cold_memory_snapshot.json");
        let content = tokio::fs::read_to_string(&path).await?;
        let records: Vec<ColdMemoryRecord> =
            serde_json::from_str(&content).unwrap_or_default();
        Ok(records)
    }

    fn build_sidecar_hint(&self, session_key: &str) -> String {
        let sidecar_path = self
            .runtime_dir
            .join("sidecar")
            .join(format!("{}.json", session_key));
        format!(
            "\n## Sidecar Feedback\n\n\
             To provide structured feedback, write JSON to:\n\
             `{}`\n\n\
             Schema: `{{\"goal\": \"...\", \"now\": \"...\", \"blockers\": [...], \"decisions\": [...], \
             \"findings\": [...], \"next_steps\": [...], \"affected_targets\": [...], \
             \"urgency\": \"low|medium|high|critical\"}}`\n\
             All fields optional. File is read on each pipeline event.\n",
            sidecar_path.display()
        )
    }
}

impl FileContextDelivery {
    /// Build the `## Memory` section from cold_memory_snapshot.json.
    async fn build_memory_section(&self) -> String {
        let records = match self.read_cold_memory().await {
            Ok(r) => r,
            Err(_) => return String::new(),
        };
        if records.is_empty() {
            return String::new();
        }
        let mut section = String::from("\n## Memory\n\n");
        for r in records.iter().rev().take(5) {
            section.push_str(&format!("- **{:?}**: {}\n", r.kind, r.summary));
        }
        section
    }
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::hot_brain::MemoryCandidateKind;
    use tempfile::TempDir;

    fn make_delivery(tmp: &TempDir) -> FileContextDelivery {
        let progress_dir = tmp.path().join("progress");
        let runtime_dir = tmp.path().join("runtime");
        std::fs::create_dir_all(&progress_dir).unwrap();
        std::fs::create_dir_all(&runtime_dir).unwrap();
        FileContextDelivery::new(progress_dir, runtime_dir)
    }

    #[tokio::test]
    async fn inject_context_writes_file() {
        let tmp = TempDir::new().unwrap();
        let delivery = make_delivery(&tmp);
        let project_dir = tmp.path().join("project");
        std::fs::create_dir_all(&project_dir).unwrap();

        // Write progress data
        let progress_file = delivery.progress_dir.join("test_session.md");
        std::fs::write(&progress_file, "- [12:00:00] **task.complete**\n").unwrap();

        // Inject context
        let result = delivery
            .inject_context("test_session", &project_dir)
            .await
            .unwrap();
        assert!(result, "should return true when context is written");

        let context_path = project_dir.join(".agent-hand-context.md");
        assert!(context_path.exists(), "context file should be created");
        let content = std::fs::read_to_string(&context_path).unwrap();
        assert!(content.contains("Agent Progress: test_session"));
        assert!(content.contains("**task.complete**"));
        assert!(content.contains("Sidecar Feedback"));
    }

    #[tokio::test]
    async fn inject_returns_false_when_no_progress() {
        let tmp = TempDir::new().unwrap();
        let delivery = make_delivery(&tmp);
        let project_dir = tmp.path().join("project");
        std::fs::create_dir_all(&project_dir).unwrap();

        // No progress file exists
        let result = delivery
            .inject_context("missing_session", &project_dir)
            .await
            .unwrap();
        assert!(!result, "should return false when no progress exists");

        let context_path = project_dir.join(".agent-hand-context.md");
        assert!(!context_path.exists(), "no context file should be created");
    }

    #[tokio::test]
    async fn read_cold_memory_empty_when_no_file() {
        let tmp = TempDir::new().unwrap();
        let delivery = make_delivery(&tmp);

        // No snapshot file exists
        let result = delivery.read_cold_memory().await;
        assert!(result.is_err(), "should error when no snapshot file");
    }

    #[tokio::test]
    async fn read_cold_memory_parses_snapshot() {
        let tmp = TempDir::new().unwrap();
        let delivery = make_delivery(&tmp);

        // Write a snapshot
        let records = vec![ColdMemoryRecord {
            id: "cold-1".to_string(),
            trace_id: "trace-1".to_string(),
            source_session_id: "session-1".to_string(),
            kind: MemoryCandidateKind::Decision,
            summary: "use JWT for auth".to_string(),
            source_refs: vec!["ref-1".to_string()],
            promoted_from: "entry-1".to_string(),
            created_at_ms: 1700000000000,
        }];
        let snapshot_path = delivery.runtime_dir.join("cold_memory_snapshot.json");
        std::fs::write(&snapshot_path, serde_json::to_string(&records).unwrap()).unwrap();

        let result = delivery.read_cold_memory().await.unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].summary, "use JWT for auth");
        assert_eq!(result[0].id, "cold-1");
    }

    #[tokio::test]
    async fn sidecar_hint_includes_path() {
        let tmp = TempDir::new().unwrap();
        let delivery = make_delivery(&tmp);

        let hint = delivery.build_sidecar_hint("my_session");
        assert!(
            hint.contains("my_session.json"),
            "hint should contain session filename"
        );
        assert!(
            hint.contains("sidecar"),
            "hint should reference sidecar directory"
        );
        assert!(
            hint.contains("Sidecar Feedback"),
            "hint should have section header"
        );
    }
}
